[aliases]
b = ["bookmark", "--no-pager"]
c = ["commit"]
d = ["diff"]
e = ["edit"]
f = ["git", "fetch"]
g = ["git"]
gi = ["git", "init", "--colocate"]
h = ["help"]
l = ["log"]
n = ["new"]
p = ["git", "push"]
r = ["rebase"]
s = ["status", "--no-pager"]

blame = ["file", "annotate"]

[merge-tools.difft]
diff-args = ["--color=always", "--display=inline", "$left", "$right"]

[revset-aliases]
C = '@+'
M = 'main'
P = '@-'
"d(x)" = 'description(x)'

[user]
name = "Dean Richer"
email = "dpbricher@gmail.com"

[[--scope]]
--when.commands = [
  "diff",
  "show",
]

[--scope.ui]
diff-formatter = "difft"
