[aliases]
b = ["bookmark"]
c = ["commit"]
d = ["diff"]
dt = ["diff", "--tool", "difft"]
e = ["edit"]
f = ["git", "fetch"]
g = ["git"]
gi = ["git", "init", "--colocate"]
h = ["help"]
l = ["log"]
n = ["new"]
p = ["git", "push"]
r = ["rebase"]
s = ["status"]
t = ["tag"]

blame = ["file", "annotate"]
# fetch latest remote and rebase current 'branch' onto main
pm = ["util", "exec", "--", "sh", "-c", """
set -e
jj git fetch
jj rebase --source 'latest((..main)+ & ..@)' --onto main
""", ""]

[merge-tools]
# aka vscode on ubuntu
code.merge-args = ["--disable-extensions", "--sync=off", "--wait", "--merge", "$left", "$right", "$base", "$output"]
difft.diff-args = ["--color=always", "$left", "$right"]

[revset-aliases]
C = '@+'
M = 'main'
P = '@-'
"d(x)" = 'description(x)'

[ui]
conflict-marker-style = "git"

[user]
email = "dpbricher@gmail.com"
name = "Dean Richer"
